apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asdf
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
