apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asdf
  namespace: argo-events
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo_cd_yaml_files/
    repoURL: https://github.com/kaan0015/argocd-test-repo.git
    targetRevision: yeni
  syncPolicy:
    syncOptions:
    - PrunePropagationPolicy=foreground

