apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  # You'll usually want to add your resources to the argocd namespace.
  finalizers:
    - resources-finalizer.argocd.argoproj.io