apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
spec:
  rules:
  - host: argocd.example.com
    http:
      paths:
       - pathType: Prefix
         path: "/"
         backend:
            service:
              name: nginx-service-preview
              port:
                number: 80 
                LoadBalancer:
                ingress:
                    - hostname: argocd.example.com