apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: example-ingress
  namespace: default
spec:
  entryPoints:
    - webb
  routes:
      # Rules to match the loginUrl and redirectUrl can be added into
      # your current router.
    - match: Host(`traefik.localhost`) && (PathPrefix(`/enter`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - kind: api@internal2
          name: github-eventsource-svc
          
  tls: {}