apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-http
  namespace: argocd
spec:
  rules:
  - host: argocd.example1.com
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: http
status:
  loadBalancer:
    ingress:
    - {}