apiVersion: v1
kind: Service
metadata:
  name: github-eventsource-svc
  namespace: default
spec:
  ports:
  - port: 12000
    name: http
    protocol: TCP
    targetPort: 12000
  - port: 443
    name: https
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
    eventsource-name: github
    type: LoadBalancer 
